name: Bug report
description: Report a reproducible problem to help us improve stability and security.
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill this out. Please search existing issues first.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Clear, concise description of the bug.
      placeholder: What went wrong?
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      description: List each step to reproduce the issue.
      placeholder: |
        1. Go to ...
        2. Run ...
        3. Observe ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs / screenshots
      description: Paste logs, stack traces, or add screenshots.
      render: shell
  - type: input
    id: version
    attributes:
      label: Version / commit
      description: Tag or commit hash if known.
  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - core
        - resource
        - tooling
        - documentation
  - type: checkboxes
    id: confirmations
    attributes:
      label: Confirmations
      options:
        - label: I searched for existing issues
          required: true
        - label: I am not sharing secrets or sensitive data
          required: true
